image: node:16-bullseye

definitions:
  steps:
    - step: &test-and-analysis
        name: Unit Test and Sonar Analysis
        script:
          - echo 'Starting pipeline'
          - node -v
          - npm -v
          - npm ci
          - npm install -g typescript@4.7.4
          # - npx tsc -v 
          - tsc
          - npx tsc
          - NODE_ENV=test npx jest --verbose --runInBand --silent --forceExit --coverage
          - ls -la
          - npm run sonar
          - echo 'Pipeline Finished'

pipelines:
  branches:
    '{master}': # or the name of your main branch
      - step: *test-and-analysis
    development: # or the name of your main branch
      - step: *test-and-analysis

